Se importan los módulos necesarios: sympy y numpy.

In [2]:
import sympy
import numpy as np
from sympy import Eq, solve, symbols, simplify, Symbol

In [22]:
# Se definen algunas variables y constantes iniciales, como Azx, Azy, x, y, k, etc
Azx = 2
Azy = 2
x = 2
y = 2
k = 20

# Se calculan los valores de ax y ay utilizando las fórmulas proporcionadas.
ax = (k * Azy) / x
ay = (k * Azx) / y

# Se imprimen los valores de ax y ay
print("ax: ", ax, "ay: ", ay)

# Se definen las variables simbólicas para poder resolver las ecuaciones
T_AMB = 30
TL = 35
TB = 35
TD = 35


ax:  20.0 ay:  20.0


In [23]:
# asume a rectangle sides
ax = symbols('ax')
ay = symbols('ay')

# asume the temperatura
TL = symbols('TL')
TB = symbols('TB')
TD = symbols('TD')
T_AMB = symbols('T_AMB')

length, height = 2, 1

In [31]:
# Se crea un arreglo T_lowers que contiene la temperatura TB repetida varias veces, y un arreglo T_upper que contiene la temperatura T_AMB repetida varias veces.
T_lowers = np.array([TB for i in range(length + 2)])
T_upper = np.array([T_AMB for i in range(length + 2)])

# Se crea un arreglo T_left con la temperatura TL, y otro arreglo T_right con la temperatura TD.
T_left = np.array([TL])
T_right = np.array([TD])

T_lowers, T_upper, T_left, T_right

(array([35, 35, 35, 35]), array([30, 30, 30, 30]), array([35]), array([35]))

In [32]:
# Se define la función concat que concatena los arreglos T_left, row, y T_right.
concat = lambda row : np.concatenate((T_left, row, T_right))

# Se crea un arreglo count_temperatures que contiene una secuencia de números del 1 al número total de temperaturas en la matriz
count_temperatures = np.arange(1, length * height + 1)

# Se crea un arreglo variables que contiene símbolos de Sympy para representar las temperaturas desconocidas en el sistema de ecuaciones.
variables = np.array([Symbol('T_' + str(i)) for i in count_temperatures])

# Se organiza la matrix de acuerdo la configuración height x length
matrix = variables.reshape(height, length)[::-1]
matrix = np.array([concat(row) for row in matrix])

# Se itera sobre las filas y columnas de la matriz y se construye la matriz matrix concatenando los arreglos T_upper, row, y T_lowers, donde row es una fila de la matriz original. 
matrix = np.concatenate(([T_upper], matrix, [T_lowers]), axis=0)[::-1]
print(matrix[::-1])


[[30 30 30 30]
 [35 T_1 T_2 35]
 [35 35 35 35]]


In [26]:
empty = np.zeros((height, length))
print(empty)

[[0. 0.]]


In [45]:
# Se crea un arreglo vacío eqts para almacenar las ecuaciones del sistema.
eqts = np.array([], dtype=Symbol)

# Se itera sobre las filas y columnas de la matriz matrix y se construyen las ecuaciones del sistema utilizando las temperaturas y coeficientes correspondientes. Estas ecuaciones se agregan al arreglo eqts.
for i in range(1, height +1):

    for j in range(1, length + 1):
        
        T_i = matrix[i][j]
        T_i_up = matrix[i + 1][j]
        T_i_down = matrix[i - 1][j]
        T_i_left = matrix[i][j - 1]
        T_i_right = matrix[i][j + 1]
        
        k_h_r = 2 if j == 1  else 1
        k_h_l = 2 if j == length else 1
        k_y_d = 2 if i == 1 else 1
        k_y_u = 2 if i == height else 1
        
        
        eqt = k_h_r * ax * (T_i_left - T_i) + k_y_u * ay * (T_i_up - T_i) + k_h_l * ax * (T_i_right - T_i) + k_y_d * ay * (T_i_down - T_i)
        eqt = Eq(eqt, 0)
        eqts = np.append(eqts, eqt)
        print(eqt, matrix[i][j])

Eq(-140.0*T_1 + 20.0*T_2 + 4000.0, 0) T_1
Eq(20.0*T_1 - 140.0*T_2 + 4000.0, 0) T_2


In [46]:
solve(eqts, *variables)

{T_1: 33.3333333333333, T_2: 33.3333333333333}

In [28]:
# Se definen algunas variables y constantes iniciales, como Azx, Azy, x, y, k, etc
Azx = 2
Azy = 2
x = 2
y = 2
k = 20

# Se calculan los valores de ax y ay utilizando las fórmulas proporcionadas.
ax = (k * Azy) / x
ay = (k * Azx) / y

# Se imprimen los valores de ax y ay
print("ax: ", ax, "ay: ", ay)

# Se definen las variables simbólicas para poder resolver las ecuaciones
T_AMB = 30
TL = 35
TB = 35
TD = 35


ax:  20.0 ay:  20.0


In [58]:

length, height = 2, 1 

eqt = np.zeros((2, 2,))
# eqt÷

result = np.zeros(height * length)

for i in range(0, height):

    for j in range(0, length ):
        print(f'{i , j = }')
        
        k_h_r = 2 if j == length - 1  else 1
        k_h_l = 2 if j == 0  else 1
        k_y_d = 2 if i == 0 else 1
        k_y_u = 2 if i == height - 1 else 1
        print(f'{k_h_r, k_h_l, k_y_d, k_y_u = }')

        eqt[j][j] += - k_h_l * ax  - k_y_d * ay - k_y_u * ay - k_h_r * ax

        if j + 1 < length:
            eqt[j][j + 1] += k_h_r * ax

        if j - 1 >= 0:

            eqt[j][j - 1] += k_h_l * ax

        if j == 0 : 
            result[j] -= k_h_l * ax * TL
        if j == length - 1 : 
            result[j] -= k_h_r * ax * TD
        if i == 0 : 
            result[j] -= k_y_d * ay * TB
        if i == height - 1 : 
            result[j] -= k_y_u * ay * T_AMB

   
print()
print(eqt)
print(result)
        

i , j = (0, 0)
k_h_r, k_h_l, k_y_d, k_y_u = (1, 2, 2, 2)
i , j = (0, 1)
k_h_r, k_h_l, k_y_d, k_y_u = (2, 1, 2, 2)

[[-140.   20.]
 [  20. -140.]]
[-4000. -4000.]


In [49]:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
x = np.linalg.solve(a, b)
x

array([-1.,  1.])

In [55]:
eqt.shape

(2, 2)

In [52]:
a.shape

(2, 2)

In [60]:
results = np.linalg.solve(eqt, result)
results

array([33.33333333, 33.33333333])

In [61]:
results = {f'T_{i + 1}': results[i] for i in range(len(results))}
results

{'T_1': 33.333333333333336, 'T_2': 33.333333333333336}