In [104]:
import sympy
import numpy as np
from sympy import Eq, solve, symbols, simplify, Symbol

In [105]:
# asume a rectangle sides
ax = symbols('ax')
ay = symbols('ay')

# asume the temperatura
TL = symbols('TL')
TB = symbols('TB')
TD = symbols('TD')
T_AMB = symbols('T_AMB')

length, height = 10, 10

In [106]:
Azx = 2
Azy = 2
x = 2
y = 2
k = 20
ax = (k * Azy) / x
ay = (k * Azx) / y

print("ax: ", ax, "ay: ", ay)
T_AMB = 30
TL = TB = TD = 35


ax:  20.0 ay:  20.0


In [107]:
T_lowers = np.array([TB for i in range(length + 2)])
T_upper = np.array([T_AMB for i in range(length + 2)])

T_left = np.array([TL])
T_right = np.array([TD])

T_lowers, T_upper, T_left, T_right

(array([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35]),
 array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30]),
 array([35]),
 array([35]))

In [108]:
def concat(row):
    return np.concatenate[T_left, row, T_right]
    

In [109]:
def concat(row):
    return np.concatenate((T_left, row, T_right))

count_temperatures = np.arange(1, length * height + 1)
variables = np.array([Symbol('T_' + str(i)) for i in count_temperatures])

matrix = variables.reshape(height, length)[::-1]

matrix = np.array([concat(row) for row in matrix])

matrix = np.concatenate(([T_upper], matrix, [T_lowers]), axis=0)[::-1]
print(matrix[::-1])


[[30 30 30 30 30 30 30 30 30 30 30 30]
 [35 T_91 T_92 T_93 T_94 T_95 T_96 T_97 T_98 T_99 T_100 35]
 [35 T_81 T_82 T_83 T_84 T_85 T_86 T_87 T_88 T_89 T_90 35]
 [35 T_71 T_72 T_73 T_74 T_75 T_76 T_77 T_78 T_79 T_80 35]
 [35 T_61 T_62 T_63 T_64 T_65 T_66 T_67 T_68 T_69 T_70 35]
 [35 T_51 T_52 T_53 T_54 T_55 T_56 T_57 T_58 T_59 T_60 35]
 [35 T_41 T_42 T_43 T_44 T_45 T_46 T_47 T_48 T_49 T_50 35]
 [35 T_31 T_32 T_33 T_34 T_35 T_36 T_37 T_38 T_39 T_40 35]
 [35 T_21 T_22 T_23 T_24 T_25 T_26 T_27 T_28 T_29 T_30 35]
 [35 T_11 T_12 T_13 T_14 T_15 T_16 T_17 T_18 T_19 T_20 35]
 [35 T_1 T_2 T_3 T_4 T_5 T_6 T_7 T_8 T_9 T_10 35]
 [35 35 35 35 35 35 35 35 35 35 35 35]]


In [110]:
eqts = np.array([], dtype=Symbol)

for i in range(1, height +1):

    for j in range(1, length + 1):
        
        T_i = matrix[i][j]
        T_i_up = matrix[i + 1][j]
        T_i_down = matrix[i - 1][j]
        T_i_left = matrix[i][j - 1]
        T_i_right = matrix[i][j + 1]

        k_h_r = 2 if j == 1  else 1
        k_h_l = 2 if j == length else 1
        k_y_d = 2 if i == 1 else 1
        k_y_u = 2 if i == height else 1

        eqt = k_h_r * ax * (T_i_left - T_i) + k_y_u*ay * (T_i_up - T_i) + k_h_l * ax * (T_i_right - T_i) + k_y_d * ay * (T_i_down - T_i)
        eqt = Eq(eqt, 0)
        eqts = np.append(eqts, eqt)
        print(eqt, matrix[i][j])

Eq(-120.0*T_1 + 20.0*T_11 + 20.0*T_2 + 2800.0, 0) T_1
Eq(20.0*T_1 + 20.0*T_12 - 100.0*T_2 + 20.0*T_3 + 1400.0, 0) T_2
Eq(20.0*T_13 + 20.0*T_2 - 100.0*T_3 + 20.0*T_4 + 1400.0, 0) T_3
Eq(20.0*T_14 + 20.0*T_3 - 100.0*T_4 + 20.0*T_5 + 1400.0, 0) T_4
Eq(20.0*T_15 + 20.0*T_4 - 100.0*T_5 + 20.0*T_6 + 1400.0, 0) T_5
Eq(20.0*T_16 + 20.0*T_5 - 100.0*T_6 + 20.0*T_7 + 1400.0, 0) T_6
Eq(20.0*T_17 + 20.0*T_6 - 100.0*T_7 + 20.0*T_8 + 1400.0, 0) T_7
Eq(20.0*T_18 + 20.0*T_7 - 100.0*T_8 + 20.0*T_9 + 1400.0, 0) T_8
Eq(20.0*T_10 + 20.0*T_19 + 20.0*T_8 - 100.0*T_9 + 1400.0, 0) T_9
Eq(-120.0*T_10 + 20.0*T_20 + 20.0*T_9 + 2800.0, 0) T_10
Eq(20.0*T_1 - 100.0*T_11 + 20.0*T_12 + 20.0*T_21 + 1400.0, 0) T_11
Eq(20.0*T_11 - 80.0*T_12 + 20.0*T_13 + 20.0*T_2 + 20.0*T_22, 0) T_12
Eq(20.0*T_12 - 80.0*T_13 + 20.0*T_14 + 20.0*T_23 + 20.0*T_3, 0) T_13
Eq(20.0*T_13 - 80.0*T_14 + 20.0*T_15 + 20.0*T_24 + 20.0*T_4, 0) T_14
Eq(20.0*T_14 - 80.0*T_15 + 20.0*T_16 + 20.0*T_25 + 20.0*T_5, 0) T_15
Eq(20.0*T_15 - 80.0*T_16 + 20.0*T_

In [111]:
solve( eqts, *variables)

{T_1: 34.9861420359221,
 T_2: 34.9598785071445,
 T_3: 34.9377445584107,
 T_4: 34.9218420785105,
 T_5: 34.9135550793772,
 T_6: 34.9135550793772,
 T_7: 34.9218420785105,
 T_8: 34.9377445584107,
 T_9: 34.9598785071445,
 T_10: 34.9861420359221,
 T_11: 34.9569737083882,
 T_12: 34.8755059413894,
 T_13: 34.8070022063987,
 T_14: 34.7579107547644,
 T_15: 34.7323782389983,
 T_16: 34.7323782389983,
 T_17: 34.7579107547644,
 T_18: 34.8070022063987,
 T_19: 34.8755059413894,
 T_20: 34.9569737083882,
 T_21: 34.9232205646296,
 T_22: 34.7781693436263,
 T_23: 34.6568475710302,
 T_24: 34.5704204951501,
 T_25: 34.5256688828533,
 T_26: 34.5256688828533,
 T_27: 34.5704204951501,
 T_28: 34.6568475710302,
 T_29: 34.7781693436263,
 T_30: 34.9232205646296,
 T_31: 34.8809597711337,
 T_32: 34.6571032974558,
 T_33: 34.4717982389459,
 T_34: 34.3412547719525,
 T_35: 34.2742079144114,
 T_36: 34.2742079144114,
 T_37: 34.3412547719525,
 T_38: 34.4717982389459,
 T_39: 34.6571032974558,
 T_40: 34.8809597711337,
 T_41: 34

In [112]:
for i in range(1, height + 1):
    for j in range(1, length + 1):
        matrix[i][j] = (matrix[i - 1][j] + matrix[i + 1][j] + matrix[i][j - 1] + matrix[i][j + 1]) / 4
print(matrix)

[[35 35 35 35 35 35 35 35 35 35 35 35]
 [35 T_11/4 + T_2/4 + 35/2 T_11/16 + T_12/4 + T_2/16 + T_3/4 + 105/8
  T_11/64 + T_12/16 + T_13/4 + T_2/64 + T_3/16 + T_4/4 + 385/32
  T_11/256 + T_12/64 + T_13/16 + T_14/4 + T_2/256 + T_3/64 + T_4/16 + T_5/4 + 1505/128
  T_11/1024 + T_12/256 + T_13/64 + T_14/16 + T_15/4 + T_2/1024 + T_3/256 + T_4/64 + T_5/16 + T_6/4 + 5985/512
  T_11/4096 + T_12/1024 + T_13/256 + T_14/64 + T_15/16 + T_16/4 + T_2/4096 + T_3/1024 + T_4/256 + T_5/64 + T_6/16 + T_7/4 + 23905/2048
  T_11/16384 + T_12/4096 + T_13/1024 + T_14/256 + T_15/64 + T_16/16 + T_17/4 + T_2/16384 + T_3/4096 + T_4/1024 + T_5/256 + T_6/64 + T_7/16 + T_8/4 + 95585/8192
  T_11/65536 + T_12/16384 + T_13/4096 + T_14/1024 + T_15/256 + T_16/64 + T_17/16 + T_18/4 + T_2/65536 + T_3/16384 + T_4/4096 + T_5/1024 + T_6/256 + T_7/64 + T_8/16 + T_9/4 + 382305/32768
  T_10/4 + T_11/262144 + T_12/65536 + T_13/16384 + T_14/4096 + T_15/1024 + T_16/256 + T_17/64 + T_18/16 + T_19/4 + T_2/262144 + T_3/65536 + T_4/16384

In [113]:
D_i = 1.1  - 2 * 0.085
D_m = D_i + 0.085
print(D_m)

N_a = 0.563 / 0.085
print(N_a)
print(8.95*(29.4 - 21.4) + 134)

1.0150000000000001
6.6235294117647046
205.6


In [114]:
from sympy import Symbol, solve, symbols, simplify, Eq

L_l = Symbol('L_l')
eqt = Eq(8.95, 134/(L_l- 29.4))
solve(eqt, L_l)

[44.3720670391061]

In [115]:
D_e = 0.56
d = 0.059

D_m = D_e - d
print(D_m)
c = D_m /d
print(c)

0.5010000000000001
8.491525423728817


In [116]:
D_e = 0.561
d = 0.055
n_a = 10 -2

D_m = D_e - d
print(D_m)
c = D_m /d
print(c)

k_m = (4*c + 2) / (4*c -3)
print(k_m)

force = 14
sigma_cortante = (8*force *k_m*D_m) / (np.pi * d**3)
print(f'{sigma_cortante:,.5g}')


G = 11.85e6

k = (pow(d, 4)* G) / (8 * pow(D_m, 3) * n_a)
print(k)

deflection = force / k
print(f'{deflection:,.5g}')



0.506
9.2
1.1479289940828403
1.2446e+05
13.07788709983973
1.0705


In [117]:
print(matrix)

[[35 35 35 35 35 35 35 35 35 35 35 35]
 [35 T_11/4 + T_2/4 + 35/2 T_11/16 + T_12/4 + T_2/16 + T_3/4 + 105/8
  T_11/64 + T_12/16 + T_13/4 + T_2/64 + T_3/16 + T_4/4 + 385/32
  T_11/256 + T_12/64 + T_13/16 + T_14/4 + T_2/256 + T_3/64 + T_4/16 + T_5/4 + 1505/128
  T_11/1024 + T_12/256 + T_13/64 + T_14/16 + T_15/4 + T_2/1024 + T_3/256 + T_4/64 + T_5/16 + T_6/4 + 5985/512
  T_11/4096 + T_12/1024 + T_13/256 + T_14/64 + T_15/16 + T_16/4 + T_2/4096 + T_3/1024 + T_4/256 + T_5/64 + T_6/16 + T_7/4 + 23905/2048
  T_11/16384 + T_12/4096 + T_13/1024 + T_14/256 + T_15/64 + T_16/16 + T_17/4 + T_2/16384 + T_3/4096 + T_4/1024 + T_5/256 + T_6/64 + T_7/16 + T_8/4 + 95585/8192
  T_11/65536 + T_12/16384 + T_13/4096 + T_14/1024 + T_15/256 + T_16/64 + T_17/16 + T_18/4 + T_2/65536 + T_3/16384 + T_4/4096 + T_5/1024 + T_6/256 + T_7/64 + T_8/16 + T_9/4 + 382305/32768
  T_10/4 + T_11/262144 + T_12/65536 + T_13/16384 + T_14/4096 + T_15/1024 + T_16/256 + T_17/64 + T_18/16 + T_19/4 + T_2/262144 + T_3/65536 + T_4/16384

In [118]:
for idx, row in enumerate(matrix):
    print(f'row {idx} is {row}')
    match idx:
        case 0:

            for i in range(1, 3):
                T_i = symbols(f'T_{i}')



            # eqt = Eq(
            #     2*ax*(TL - T_i) + ay*(TB - T_i) + ax*(T - T_i) + 4*ax*(T_AMB - T_i),
            #     0
            # )


row 0 is [35 35 35 35 35 35 35 35 35 35 35 35]
row 1 is [35 T_11/4 + T_2/4 + 35/2 T_11/16 + T_12/4 + T_2/16 + T_3/4 + 105/8
 T_11/64 + T_12/16 + T_13/4 + T_2/64 + T_3/16 + T_4/4 + 385/32
 T_11/256 + T_12/64 + T_13/16 + T_14/4 + T_2/256 + T_3/64 + T_4/16 + T_5/4 + 1505/128
 T_11/1024 + T_12/256 + T_13/64 + T_14/16 + T_15/4 + T_2/1024 + T_3/256 + T_4/64 + T_5/16 + T_6/4 + 5985/512
 T_11/4096 + T_12/1024 + T_13/256 + T_14/64 + T_15/16 + T_16/4 + T_2/4096 + T_3/1024 + T_4/256 + T_5/64 + T_6/16 + T_7/4 + 23905/2048
 T_11/16384 + T_12/4096 + T_13/1024 + T_14/256 + T_15/64 + T_16/16 + T_17/4 + T_2/16384 + T_3/4096 + T_4/1024 + T_5/256 + T_6/64 + T_7/16 + T_8/4 + 95585/8192
 T_11/65536 + T_12/16384 + T_13/4096 + T_14/1024 + T_15/256 + T_16/64 + T_17/16 + T_18/4 + T_2/65536 + T_3/16384 + T_4/4096 + T_5/1024 + T_6/256 + T_7/64 + T_8/16 + T_9/4 + 382305/32768
 T_10/4 + T_11/262144 + T_12/65536 + T_13/16384 + T_14/4096 + T_15/1024 + T_16/256 + T_17/64 + T_18/16 + T_19/4 + T_2/262144 + T_3/65536 + 

In [119]:
array = np.arange(1, 6)
for i in array:
    
    T_i = symbols(f'T_{i}')

    match i:
        case 1 :
            T = symbols(f'T_{i + 1}')
            T_upper = symbols(f'T_{i + len(array)}')
            eqt = simplify(Eq(
                2*ax*(TL - T_i) + ay*(TB - T_i) + ax*(T - T_i) +  2*ay*(T_upper - T_i),
                0
            ))

print(eqt)

Eq(-120.0*T_1 + 20.0*T_2 + 40.0*T_6, -2100.0)
